### ISSUE TITLE
Add .editorconfig file with commom coding styles

### ISSUE THREAD

**Issue by odahcam** [mburst/dijkstras-algorithm#15]
I realised that the algoritms are very different in coding design style. 

This can make things harder for newbies, cause the scripts look too different.

Similar scripts will increase the recognition capability between different languages will and make things easier to understand in a generic approach.

**Comment by mburst** [comment]
Different languages tend to have different preferred programming styles and conventions. This repo is more to learn about the algorithm implementation rather than the code style. Since there is only one implementation per language allowed I think it's ok to skip on the editorconfig, though I do like editorconfigs for larger repos.

**Comment by odahcam** [comment]
I agree, but thing like tabs instead of spaces and windows or unix line breaks are universal, maybe it stills good.
